/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package gcs2417

class App {
    String getGreeting() {
        return 'Hello world.'
    }

    static void main(String[] args) {
        String configRaw = '''
        top {
          // 2.4.17 parses main as a config 
          // 2.5.0+ try to invoke it as the main method
          main { 
            prop1 = 1
            prop2 = 2
            prop4 = 'four'
          }
          other {
            other1 = 'something'
          }
          prop3 = 3
        }
        '''
        ConfigSlurper cs = new ConfigSlurper()
        ConfigObject config = cs.parse(configRaw)
        println new App().greeting
    }
}
